### ISSUE TITLE
Relicense

### ISSUE THREAD

**Issue by Emerentius** [aochagavia/sudoku#7]
I should have probably thought of this before agreeing to become a collaborator but oh well, here we are.

Recently my goals for this library expanded a bit. I'd like to have
* a very fast solver
* sudoku generation with some kind of difficulty configuration
* good error reporting for impossible sudokus (should be quite simple actually)
* a solver capable of pluggable human strategies and step-by-step solving and hinting
  Basically, it should be possible to implement something [like this](http://www.sudokuwiki.org/sudoku.htm) with no sudoku logic of your own.
* (maybe) support for non-standard sudoku sizes

So far we only have a quick-enough solver. When the library has reached the above state it would be suitable as a base for some kind of app and while I don't think the scenario likely as of now, given how much sudoku stuff there already is, I don't want my code to be a part of some proprietary software.

I didn't care so far because it was more or less a toy implementation. Now, I'd like to continue development under the AGPLv3. I'm not sure if you're aware of its terms, @aochagavia. It's basically the GPLv3 with the additional clause that network use counts as distribution and requires open sourcing.

Offtopic:
I'm going to be travelling for a couple of months from May on. I'd like to push my local work before that. I've adopted Jsolve's algorithm (for the most part) for the solver which is the fastest sudoku solver I'm aware of. I couldn't quite achieve its speed, yet, but I got within 66%-90% of its performance depending on sudoku set which is still 15x as fast as the current solver for hard sudokus.

**Comment by aochagavia** [comment]
I am not sure about this. Let me explain below.

My main concern is that I never intended this to become the go-to library for sudoku solving and generation in Rust, which seems to be the direction things are taking. I don't have the time or the interest to maintain something like that. As you correctly pointed out, this was for a long time just a toy implementation, published just in case someone would find it useful (which seems to be the case, judging by the 1000+ downloads on crates.io)

From that perspective, I propose that:

1. You create a fork of this crate, and work further from there
1. I relicense my code on your fork (which is almost non-existent at this point). This crate will stay under MIT (if you want, I could remove all your commits after you fork it)
1. I transfer ownership of the `sudoku` name on crates.io to you, since it makes no sense to keep such a great name for a toy crate when there is a good one available

What do you think about this?

**Comment by Emerentius** [comment]
Yes, a handover is also fine. There's no need to remove my old commits. They can stay MIT. It's not like I could revoke that license anyway nor would I want to.

Though I'd just like to say, all of my goals are long term. It'll be a while until this takes shape. For the next 3 months I won't even have access to a rust compiler at all.

Edit: Right, apparently you can't make a fork into its own fully owned project. So I recreated it and I'm opening an issue there to request permission to relicense and link that to this one.
